project_id = "rxkhtqezcyaqvjlbzzpu"

[functions.invite-user]
verify_jwt = false

[functions.purge-all-test-data]
verify_jwt = false

[functions.purge-week]
verify_jwt = false

[functions.purge-transport-week]
verify_jwt = false

[functions.notify-conducteur]
verify_jwt = false

[functions.rappel-chefs]
verify_jwt = false

[functions.rappel-chefs-lundi]
verify_jwt = false

[functions.rappel-conducteurs]
verify_jwt = false

[functions.rappel-conducteurs-finisseurs]
verify_jwt = false

[functions.purge-affectations-finisseurs]
verify_jwt = false

[functions.purge-orphan-fiches]
verify_jwt = false

[functions.create-test-data-s45]
verify_jwt = false

[functions.purge-affectations-macons]
verify_jwt = false

[functions.purge-entreprise-weeks]
verify_jwt = false

[functions.purge-entreprise-complete]
verify_jwt = false

[functions.sync-planning-to-teams]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false